name: sbruch-assignment-lwmd
channels:
  - conda-forge
#  - pytorch
dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - jupyter
  - jupytext
  - nltk
  - seaborn
  - nb_conda_kernels
  - loguru
  - transformers
  - sentence-transformers
#  - torchvision
#  - torchaudio
#  - pytorch-cuda=11.8
  - pip
  - pip:
      - beir
      - rank_bm25